#!/bin/sh
if [ "$DOCKER_TAG" = "dev" ]
  then docker build --build-arg BW_BRANCH="develop" --build-arg BW_REPOSITORY=$BW_REPOSITORY -f $DOCKERFILE_PATH -t $IMAGE_NAME .
  else docker build --build-arg BW_BRANCH=$BW_BRANCH --build-arg BW_REPOSITORY=$BW_REPOSITORY -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi